{% set version = "2.0.3" %}

package:
  name: pyhamcrest
  version: {{ version }}

source:
  fn: PyHamcrest-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/P/PyHamcrest/PyHamcrest-{{ version }}.tar.gz
  md5: f628e2ff2b6a2518f54b15d70ac34c9d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools

  run:
    - python >=3.5

test:
  imports:
    - hamcrest
    - hamcrest.core
    - hamcrest.core.core
    - hamcrest.core.helpers
    - hamcrest.library
    - hamcrest.library.collection
    - hamcrest.library.integration
    - hamcrest.library.number
    - hamcrest.library.object
    - hamcrest.library.text

about:
  home: https://github.com/hamcrest/PyHamcrest
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Hamcrest framework for matcher objects

extra:
  recipe-maintainers:
    - duncanwp
    - stuertz
